version: "3.8"
services: 
  app:
    build: ./app/
    image: first-ml-service:latest
    container_name: first-ml-service-container-app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    restart: unless-stopped
    env_file:
    - ./app/.env
    volumes:
      - ./app:/app

  web:
    image: nginx:latest
    container_name: first-ml-service-container-nginx
    restart: unless-stopped
    ports:
      - '443:8000'
      - '80:8000'
    volumes:
      - ./html5up-stellar/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    
  db:
    image: postgres:latest
    container_name: first-ml-service-container-db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:latest
    container_name: first-ml-service-container-rabbitmq
    hostname: rabbitmq
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - '5672:8888'
      - '15672:8888'
volumes:
  postgres_data:



